version: '2'
services:
    plamob-app:
        image: plamob
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://plamob-postgresql:5432/plamob
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    plamob-postgresql:
        extends:
            file: postgresql.yml
            service: plamob-postgresql
